version: '2'

services:
  db:
    image: postgres
    ports:
      - "5432"
    environment:
      POSTGRES_PASSWORD: postgres
  backend:
    build:
      context: footvote-backend
      args:
        UID: ${UID:-1001}
    volumes:
      - ./footvote-backend:/usr/src/app
      - ./footvote-backend/tmp/cache:/usr/src/app/tmp/cache
    ports:
      - "127.0.0.1:8080:8080"
    depends_on:
      - db
    user: rails
  frontend:
    build:
      context: footvote-frontend
      args:
        UID: ${UID:-1001}
    volumes:
      - ./footvote-frontend:/usr/src/app
    ports:
      - "127.0.0.1:3000:3000"
    user: frontend

  nginx:
    image: nginx:stable
    depends_on:
      - backend
      - frontend
    links:
      - backend
      - frontend
    volumes_from:
      - backend
      - frontend
    volumes:
      - ./nginx/development/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/development/footvote.conf:/etc/nginx/sites-enabled/footvote
      - ./nginx/development/tmp/error.log:/var/log/nginx/error.log
      - ./nginx/development/tmp/access.log:/var/log/nginx/access.log
    ports:
      - "80:80"
      - "443:443"
