version: '3'
services:
  db:
    image: postgres
    ports:
      - "5432"
    environment:
      POSTGRES_PASSWORD: postgres
  backend:
    build:
      context: footvote-backend
      args:
        UID: ${UID:-1001}
    volumes:
      - ./footvote-backend:/usr/src/app
    ports:
      - "8080:8080"
    depends_on:
      - db
    user: rails
  frontend:
    build:
      context: footvote-frontend
      args:
        UID: ${UID:-1001}
    volumes:
      - ./footvote-frontend:/usr/src/app
    ports:
      - "3000:3000"
    user: frontend
