default: &default
  adapter: postgis
  encoding: unicode
  host: db
  username: postgres
  password: postgres
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: footvote_backend_development

test:
  <<: *default
  database: footvote_backend_test

production:
  adapter: postgis
  encoding: unicode
  host: localhost
  database: footvote_backend_production
  username: footvote_backend
  password: <%= Rails.application.credentials.db.fetch(:password, 'postgres') %>
